// @ts-nocheck
import{myError}from"../dom/domUtils.js";export async function handleError({filename:r,consoleMsg:e,err:o,userMsg:t=null,errorEle:n=null}){try{const[s,l]=await Promise.all([import("./errorMessages.js"),import("./errorLogs.js")]),{helpDeskTicket:a}=s,{default:i}=l;if(await i(r,e,o),t&&n){myError(n,`${t}<br>${a}`)}}catch(r){if(console.warn("Error while handling error:",r),n){const r="string"==typeof n?document.getElementById(n):n;myError(r,"An unexpected error occurred. Please try again.")}}}